PythonTools/MQ.py

Uses getpass.getuser() to always detect the current username.

fixed MQ.py hard-coded username now autodetects x-platform

---

PythonTools/MBuild.py
buildOptions.txt

Added the '-' flag to complement '+' so lines don't need to be deleted. This was done because I found it annoying having to traverse directories just to remember what things were called that I had deleted from the file. You can still delete lines if that suits your fancy.
I also improved commenting of buildOptions parsing and added error reporting along with line number tracking, so the user knows specifically where they messed up if they did.
Lastly, now that there is an official way to have lines for modules present but not added to the build, then I've restructured the file so all but a minimal selection test environment and example additional module are enabled by default. This results in a fast "does it build?" first experience for new users, instead of having to wait for an …

Feature no delete build options lines

---

main.cpp

Fixes #34. MinGW random_device is not random, but all other compilers appear to implement it correctly. So when compiled on MinGW, the RNG is seeded with the PID which requires including<windows.h>.

Hotfix RNG on win now seeded with PID

---

main.cpp

The old logo (while cool when printed!) was difficult to see and work with in source. The new implementation uses raw strings to resolve this. The URL was also updated to match the new repository location.

Hotfix implementation of the logo, and updated the github project URL.

---

PythonTools/MBuild.py

MBuild.py would exit with the following message: `option '--generate' or '-g' was given an unsupported project file type. Valid types are: make,vs,xcode,devcpp,cb`

MBuild.py exit when -g was not given

---

.gitignore
Utilities/zupply.cpp
Utilities/zupply.h

VS produces an error when:
- cmakelists.txt files are present that should not be, so now they are .gitignored
- using <atomic> without a special VS define that says we know what we're doing

fixes vs build error with zupply

---

pythonTools/mq.py

This patch allows using mq without specifying any VARS or CONDITIONS, so just running a replication job.

allow mq with no vars or conditions

---

pythonTools/mq.py
pythonTools/mq_conditions.txt

Allow {{rep}} syntax in mq_conditions files which are replaced with the current rep number. Useful for population loading / analysis use cases.

adds {{rep}} keyword to mq_conditions

---

Utilities/Loader.cpp
Utilities/Loader.h
Utilities/Parameters.cpp
Utilities/Parameters.h
main.cpp

initPop can now optionally take a *.plf file as an argument, or a single line with plf syntax.
organsims can be chosen from disk where attribute values match exactly the provided value ( this value is treated as a string, to avoid problems like double precision, etc)
Note: main() will crap out if plf doesn't manage to load even a single org.
Note: values in settings files can now contain spaces, so long as the entire value is on a single line.

Enhance pop loader

---

Utilities/Utilities.h

seq() may return empty list, but exits gracefully on incorrect input syntax.

seq() gives error message and exits on input with incorrect syntax

---

Utilities/Parameters.cpp

command line arguments using -p can now be passed as literal-quoted strings.
e.g. 
./mabe -p GLOBAL-updates 10
is the same as 
./mabe -p GLOBAL-updates \"10\"
This allows multi-word Parameters to be passes to mabe via the command line.

allow true-quoted strings as command line parameters

---

Utilities/Loader.cpp

For every organism file, the corresponding data file might need to be used, so we add that to the list of all possible file names.

pop loader looks at corresponding data file to use the attributes

---

.travis.yml
pythonTools/mbuild.py
pythonTools/mgraph.py
pythonTools/mq.py
pythonTools/utils/pyreq.py

This makes the mTools code cleaner and reduces code duplication. We can also reuse this tool in the future. It looks for python installers: conda,pip3,pip in that order.
Usage looks like this:
```
from utils import pyreq
pyreq.require("installNameA,installNameB:importNameB") ## quits if it had to install stuff for you
import installNameA, importNameB
```
After installation, it says you should now be good to go to rerun the script you were trying to run, without issues.

refactored, fixed, and updated the 'required modules auto install' code

---

.travis.yml
pythonTools/mbuild.py
pythonTools/mgraph.py
pythonTools/mq.py
pythonTools/utils/pyreq.py

Adds following command: "python pythonTools/mbuild.py -i" or "python pythonTools/mbuild.py --init" which does the following:
- discovers all mabe modules that should go into buildOptions.txt
- refreshes or creates buildOptions.txt
- only adds modules that aren't already in buildOptions.txt (so leaving current include ops)
- removes modules that don't exist in the filesystem anymore
- prints to screen before quitting, the new buildOptions.txt content

Feature build options gens

---

Brain/MarkovBrain/MarkovBrain.cpp

moved parameters and renamed so they are together, changed default file name, changed datamap outputBehavior so that only lists are saved

Hotfix mb io mapping cleanup

---

Organism/Organism.cpp
Organism/Organism.h
World/AbstractWorld.h
World/TestWorld/TestWorld.h
World/XorWorld/XorWorld.cpp
World/XorWorld/XorWorld.h

removed AbstractWorld function evaluateSolo (and updated Xor world) AND removed genome and brain from Organism. These features had been deprecated but remained in the code for backward compatibility.

Deprecate old world and organism functions

---

Utilities/Parameters.cpp

namespace closes correctly, with error on incorrect close.
mabe exits if Parameter file is dirty.

fixed namespace closing. Also cause exit(1) on dirty Parameters file

---

pythonTools/mbuild.py

Needs testing on OSs.
Tested on:

upgrading to c++14

---

Utilities/Utilities.h

the seperator argument was not effective after the first call because the static regex was not being reassigned.

changed regex definition in parseCSVLine to not be static

---

Utilities/Parameters.cpp

Parameters in settings files can now be 
%
AA-val = 1
or 
% AA
val =1 
Both mean the same.
Fixes #208

short style category names allowed

---

main.cpp

Has been tested on:
I've been meaning to add this for quite a while.
Provides a better user experience than killing MABE in a potentially bad state (before, sometimes it would keep running).
- On first ctrl-c tells user it will quit after current update
- And tells them to do it again to force quit immediately if they don't want to wait
`"\nQuitting after current update. (ctrl-c again to force quit)\n"`
- Allowing MABE to finish current update finishes evolution loop and flushes LOD etc. as usual.
You can test the full functionality by making a giant population size, so updates take a while.

added ctrl-c handler

---

Utilities/Parameters.cpp

-p option swallows the first command line flag immediately following name-value pairs. Fixed.

Patch dont run on save

---

Utilities/Parameters.cpp
Utilities/Parameters.h

Basically makes layout in Parameter files cleaner. If parameter name goes over the commentIndent, comment is chopped. If parameter name goes over maxLineLength, the comment is started on the following line.
More lines changed than strictly necessary, but it's only clean up.

Patch wrap parameter

---

pythonTools/mq.py

Fixes #114 (mostly)
- adds `':'` as one of the scrubbed characters from dir names.
- removed stripping of `'['` and `']'` from parameters
- fixed regex capturing all value assignments in conditions line (`\S` to `\s`)
- auto strip `"` double quote from each parameter value if it's the first and last char. NOTE! This implies you cannot pass strings with spaces in them to MABE.
- fixed multiple equals found in conditions line

Hotfix mq cmd call

---

Utilities/Loader.cpp

Wildcard was converted to expand only to characters. Now it expands to match everything but the '/'

corrected wildcard conversion

---

Utilities/MTree.h

the MTree class had a parent pointer. this was not being assigned correctly in almost all cases. In the cases it was being assigned, it resulted in a circular shared ptr reference. parents are no more.

Hotfix MTree

---

Archivist/DefaultArchivist.cpp

This fixes a long standing bug (which only now came to light) where 'update' was not being saved in Default Archivist snapshot files. 'Update' is now being saved in these files.

change to Default Archivst so that update is saved in data files

---

Analyze/neurocorrelates.cpp

Fixes #264 by removing the line declaring log2 and pow as members of std namespace. `#include <math.h>` takes care of these declarations and the feature should work as before.

Remove log2 and pow declarations in neurocorrelates

---

Utilities/Parameters.cpp

Clang update October 2018 has a special definition of whitespacing vs non-whitespacing that broke a regex. This reverts and and patches for compliance.
namespace under category headings still does not work, must be fully qualified.

changed regex for compliance on new mac clang whitespacing definitions

---

Global.cpp
Utilities/Loader.cpp

Change behaviour of initPop parameter. The "MASTER = " piece of .plf syntax is now implicit, and cannot be specified. 
Default argument of initPop, and usage message is also updated.

changed behaviour and usage message

---

Analyze/neurocorrelates.py

Use by doing:
```
from Analyze.neurocorrelates import R
R(states_over_time_list)
```
This is different from the C++ version.
C++ version single timepoint state recording has sensor, environment, and memory state vectors elided together:
```
[0,1,1,0,0,1,1,0,1]
```
python version keeps the sensor, environment, and memory state vectors separate:
```
[[0,1,1,0],[0,1,1],[0,1]]
```
So using R in python becomes:
```
mystates_for_2_timepoints = [[[0,0,1,0,1,0,1],[0,1,1,0,1,1],[0,0,1,1]],
[[1,1,1,1,0,1,0],[1,0,1,1,0,0],[1,1,0,0]]]
r_value = R(mystates_for_2_timepoints)
```

added R measure in python

---

Genome/CircularGenome/CircularGenome.cpp
Genome/MultiGenome/Chromosome/TemplatedChromosome.cpp

change read and write double for non-double types before it would not return the upper bound. i.e. readDouble(0.0,10.0) could not return 10.0, it could return at max (10.0 - 1/aphabetSize). Now it can return 10 it will if the site value is aphabetSize - 1.

change read and write double for non-double types

---

pythonTools/mbuild.py

added a new command line argument "-do" or "--debugOptimization"  that changes optimization from -O3 to -g -O0 to allow for debuggers to hook in properly when necessary. This greatly affects the ability of programs like gdb and valgrind to give human readable output and accurate line numbers when they detect bugs.

debug compile flag option

---

Utilities/Loader.cpp

The following assignment to all_lines reallocates it:
`all_lines = m.prefix().str() + " " + new_tk + " " + m.suffix().str();`
Meanwhile, the std::smatch object retains a pointer to it which is invalidated by the assignment. When it is accessed at
`auto exp_files = expandFiles(m[1].str());`
it reads some deallocated memory.
In most cases this won't change the behavior of the program, but first, there are no guarantees, and second, the invalid read pollutes the output of memory analyzers, making it more difficult to debug newly added code.

Fix for the invalid memory read in one of the parsers of Loader.cpp

---

Utilities/Loader.cpp

modified:   Utilities/Loader.cpp
Tiny change to Loader.cpp that prevents Loader::find_and_generate_all_files from reading a deallocated string.

Fix for the invalid memory read in Loader.cpp

---

pythonTools/mq_conditions.txt

Having a commented-out line after the HPCC_PARAMETERS and #SBATCH tags was causing vim to throw an error when opening up the file, because it thought we were trying to declare a parameter called FAIL,END,REQUIRE.
The error did not actually affect anything (jobs ran as requested), but repeatedly seeing this error was annoying me, so i moved the comment before the parameters.

Fixed error message resulting from confusing parsing

---

Brain/MarkovBrain/MarkovBrain.cpp

Prior to this commit, Markov Brains did not reset IO buffers
inherited from AbstractBrain upon the call to reset(). The buffers
were used by Markov Brains and the state they retained affected
their behavior.
modified:   Brain/MarkovBrain/MarkovBrain.cpp

Fix for the MarkovBrains IO reset issue

---

Utilities/Utilities.h

In the vectorToBitToInt utility function a temporary container
in which the node addresses were stored in appropriate order
is replaced by iterating over the original container in
appropriate direction. Memory reallocation is thus avoided.
This function is called at every call of DeterministcGate::update().
In the codes that rely heavily on MarkovBrains' deterministic gate,
this optimization cuts execution time approximately by a quarter.
modified:   Utilities/Utilities.h

MarkovBrain execution time optimization

---

CMakeLists.txt
buildOptions.txt
pythonTools/libmbuild/projectwriter.py
pythonTools/mbuild.py

First part of a deprecation of mbuild.py project generation.
The functionality has been replaced by a cmake out of source workflow:
1) git clone mabe (shorthand)
2) edit mabe/buildOptions.txt
3) mkdir build
4) cmake ../mabe -G <project type>
where makefiles are default, and your system may support: Visual Studio, XCode, CodeBlocks, Ninja, and others.
Benefits:
* Out of source workflow to not dirty the repo clone.
* A more standard software practice that is no more difficult than we had before.
* We don't have to support project generation code anymore.
* buildOptions now allows adding custom cmake fragments as filenames, which opens the door to easily adding external libraries (ex: 3d graphics, fast linear algebra, etc.)
Note, for Visual Studio, you will need to be in a Visual Studio …

added cmake out of src workflow

---

Genome/CircularGenome/CircularGenome.cpp
Genome/CircularGenome/CircularGenome.h

Primarily this fixes a bug where indel mutation on circular genome was not able to effect the last site in the genome (random getIndex was used rather than getInt). Also, this adds a new feature to allow for normal distribution of point mutation.

Bugfix genome circular indel mutation

---

Genome/CircularGenome/CircularGenome.cpp

There was some cout left in CircularGenome writeDouble() method, so the screen was spammed with debug output at the start of a run.

removed writeDouble debug output
