- Optimizer/GAOptimizer/GAOptimizer.cpp
replace:
if (elitismLPL->lookup()) {     <-- this is a bug!
with:
if ((int) nextPopulation.size() < elitismLPL->lookup()) {
> fix bug in GAOptimizer

- PythonTools/MQ.py
This needs testing with MQ_conditions with many replicates: can we spawn infinite threads and the OS handles it?
> Added multithreading job submission

- PythonTools/MQ.py
- PythonTools/MQ_conditions.txt
Added the 'conditions' feature we discussed several months ago. It is implemented as a non-breaking change, however it is recommended to deprecate the older use of VAR/EXCEPT, which may require modifications of how VAR works, since values are not necessary to specify on the VAR line when using CONDITIONS.
Also updated args for continuity, and included a commented out example of how to use CONDITIONS in MQ_conditions.txt.
> Feature mq conditions

- PythonTools/MBuild.py
- Utilities/Loader.cpp
- Utilities/Loader.h
Simply added Loader.h and Loader.cpp. And modified MBuild to always compile this correctly.
> Population loading mechanism

- PythonTools/MQ.py
- PythonTools/MQ_conditions.txt
Adds:
- warnings for mismatched [],() in MQ_conditions.txt values
- color coding for errors and warnings
- auto py module detection and installation
- full [] list conformant behavior in MQ_conditions.txt values like settings files
- bad dir name characters removed for conditions directories (from values)
> Feature mq openclose error checking

- Utilities/graycode.h
Adds graycode utility functions in Utilities under Graycode::graycode and Graycode::ungraycode.
Deals with unsigned int only and appropriately converts negative to positive.
> added graycode library

- Testing/makefile
- Testing/test_graycode.h
- Testing/tests.cpp
Added a Testing folder containing:
- Google Testing Framework (provided by makefile)
- makefile to build all tests
- Example of how to build modular tests
> added unit testing framework, and tests for graycode

- Utilities/Loader.cpp
Implemented cross platform file discovery in lieu of c++17 <filesystem> we can't wait for.
> Hotfix loadpop filesystem

- Utilities/Loader.cpp
small bug had been created in melding the new library with existing usage.
> fixed relative path bug from new lib implementation

- Utilities/zupply.cpp
- Utilities/zupply.h
The author merged a PR we submitted for building on the newer GCCs.
This PR here is change the tracking state back from my PR branch to the author's master branch.
Documentation added in the shortcut files in Utilities/zupply.{cpp,h} about what they are and how to update the library using git subtree.
> Feature zupply update and doc

- World/ComplexiPhiWorld/ComplexiPhiWorld.cpp
- World/ComplexiPhiWorld/ComplexiPhiWorld.h
- World/EdlundMazeWorld/EdlundMazeWorld.cpp
- World/EdlundMazeWorld/EdlundMazeWorld.h
- World/PathAssociationWorld/PathAssociationWorld.cpp
- World/PathAssociationWorld/PathAssociationWorld.h
- World/PendulumWorld/PendulumWorld.cpp
- World/PendulumWorld/PendulumWorld.h
- World/ValueJudgmentWorld/ValueJudgmentWorld.cpp
- World/ValueJudgmentWorld/ValueJudgmentWorld.h
- World/XorWorld/XorWorld.cpp
- World/XorWorld/XorWorld.h
- buildOptions.txt
Added the following new problem domains:
- ComplexiPhi (recreated from block-catching Marstaller 2013)
- EdlundMaze (recreated from maze-solving Edlund et al. 2011)
- PathAssociation (recreated from association memory Anselmo Pontes' unpublished dissertation)
- ValueJudgment (recreated from Kvam et al. 2015)
- Pendulum (the standard inverted pendulum problem)
- Xor (simple xor)
> added 6 new worlds

- World/SymbolNavWorld/SymbolNavWorld.cpp
- World/SymbolNavWorld/SymbolNavWorld.h
- buildOptions.txt
Sheneman-based port with what might be fixes.
> Feature world symbol nav

- .travis.yml
Successful Travis CI build sequence after upgrade.
> trying new code after the travis upgrade

- README.md
- Utilities/Parameters.cpp
> Hotfix random seed cli

- Utilities/Loader.cpp
> Fixed duplicate same-name population selection. Also fixed 'worst' selection

- Utilities/Loader.cpp
> Fixed duplicate population selection. Also fixed 'worst' selection

- Archivist/DefaultArchivist.cpp
- Archivist/LODwAPArchivist/LODwAPArchivist.cpp
- Archivist/SSwDArchivist/SSwDArchivist.cpp
- Examples/World/EXampleWorld_cpp
- Examples/World/EXampleWorld_h
- Examples/World/ExampleWorldClean_cpp
- Examples/World/ExampleWorldClean_h
- Optimizer/SimpleOptimizer/SimpleOptimizer.cpp
- Utilities/Loader.cpp
- World/AbstractWorld.h
- World/BerryPlusWorld/BerryPlusWorld.cpp
- World/BerryPlusWorld/BerryPlusWorld.h
- World/TestWorld/TestWorld.cpp
- World/TestWorld/TestWorld.h
- World/XorWorld/XorWorld.cpp
- World/XorWorld/XorWorld.h
> Hotfix spelling

- Utilities/Loader.cpp
> population loader best and worst swapped correctly

- Utilities/Loader.cpp
> Hotfix pop loader best worst

- pythonTools/mbuild.py
Added output for error before exit
> Feature m build error notification improvement

- Brain/MarkovBrain/MarkovBrain.cpp
- Brain/MarkovBrain/MarkovBrain.h
Adds a function for accessing hidden nodes in Markov Brains for analysis
> Feature get hidden nodes mb

- Utilities/Loader.cpp
- Utilities/Loader.h
- Utilities/Parameters.cpp
- main.cpp
Fixes #127 and does some renaming
> Renamed best/worst to greatest/least and updated eg usage file

- Utilities/Loader.cpp
- Utilities/Loader.h
- Utilities/Parameters.cpp
- main.cpp
Fixes #127  and does renaming...
> Hotfix pop loader

- pythonTools/mgraph.py
Note: this merge will change the default behavior of mgraph.
Added 'sem', '95conf', and '99conf' as parameters to -pltWhat (Standard Error from the Mean, 95% confidence, 99% confidence).
Renamed 'error' to 'std' in -pltWhat to more accurately reflect the mathematics being done.
Set the default behavior to [ave, 99conf], instead of [ave, std] (previously [ave, error]).
Removed a depreciated and unused parameter 'ErrorMethod'.
> Feature mgraph statistics upgrade

- main.cpp
- pythonTools/mgraph.py
95% confidence interval patch breaks usage of mgraph.py in case of NO replicates being plotted.
> Patch revert mgraph

- pythonTools/mgraph.py
Reinstating confidence intervals along with an additional change that allows confidence intervals to be graphed in the absence of the actual average line.
NOTE: Python library Pandas needs to be version 0.15.2 or higher to have access to the dataframe.sem() function. The wiki needs to be updated to reflect this requirement once this branch has been merged
> Hotfix mgraph confidence bugfix

- Utilities/Utilities.h
> Fix for non-matching quotes and square brackets

- Utilities/Loader.cpp
This gives a considerable speedup since std::regex construction is expensive.
> declared all regexs to be static const to avoid multiple construction

- Utilities/Loader.cpp
- Utilities/Loader.h
To make duplicate copies, use the following syntax e.g.
3 * 'LOD_organisms.csv'
will create a collection of 3 identical populations, each of which contains the entire population from the LOD_organisms.csv file.
> Feature pop loader each

- Utilities/MTree.h
Fixes bug on unqualified abs().
> ambigious call to unqualified abs

- main.cpp
instead of hard coding the parameter to zero.
> allows for the world debug flag to be set during visualize mode 

- Archivist/DefaultArchivist.cpp
> From note on lowest in N4659:21.3.4.1

- pythonTools/utils/pyreq.py
> pyreq now always install modules into user dir (--user)

- Optimizer/SimpleOptimizer/SimpleOptimizer.cpp
updated algorithm for cullRemap function. Better config messages.
> Hotfix fix simple optimizer cull below

- .gitignore
- Archivist/DefaultArchivist.h
- Optimizer/AbstractOptimizer.h
- Organism/Organism.h
- Utilities/Data.h
- Utilities/MTree.h
- Utilities/Utilities.h
- Utilities/gitversion.h
- World/AbstractWorld.h
Changed all c-headers to c++-headers.
Except in MarkovBrain, since that needs a major rewrite anyway.
Also, plenty of files have superfluous headers. I removed the ones in  Utilities/Data.h  only. If anyone wants to take this on, feel free.
Also, ignore the .gitignore.
> Patch c headers

- Optimizer/IslandsOptimizer/IslandsOptimizer.cpp
- Optimizer/IslandsOptimizer/IslandsOptimizer.h
- buildOptions.txt
new (meta) optimizer which creates islands of organisms each with its own simple optimizer and allows for migration between islands.
> Feature island optimizer

- Global.h
> Patch dep pls

- pythonTools/mgraph.py
r/ in out file name replaced with _. a save name can be specified but only if one file will be saved (otherwise exit with a useful message).
> change to mgraph to imporve file output names.

- Analyze/neurocorrelates.cpp
- Analyze/neurocorrelates.h
- pythonTools/mbuild.py
Adds the ability to use the neurocorrelates to analyze brains
> Feature neurocorrelates

- .travis.yml
- appveyor.yml
Adds Appveyor(windows) and Travis(osx) support, in addition to the Travis(linux) support that already exists.
> Appvyrtest

- Genome/CircularGenome/CircularGenome.cpp
- Genome/CircularGenome/CircularGenome.h
- README.md
Allows tracking of point, copy, and deletion mutations only on circular genomes.
> Feature Circular Genome mutation tracker

- Utilities/Utilities.h
updated vectorToTritToInt to match Bit version, and cleaned up the formatting on this and Bit version.
> updated vectorToTritToInt

- pythonTools/mq.py
Adds the -i, --indefinite mode (implies -d HPCC deployment).
Kills and resubmits jobs every 3 hours 50 minutes.
This is old code I had from a couple years ago - seems to still work okay so I'm merging it for others to benefit.
Changes are all in mq.py, adding a large string that is the template for the sbatch submission file.
Ideally, this should be read from an external sbatch template file that would be easier to update.
> mq longjob feature added

- pythonTools/mbuild.py
changes a
```py
'' + number + ''
```
to
```py
'' + str(number) + ''
```
> fixed python38 mbuild issue with str/int concat

- Archivist/LODwAPArchivist/LODwAPArchivist.cpp
change to support LOD and overlapping generations
> change to support LOD and overlapping generations

- tools/mq.py
This fixes a bug where partial results between indefinite mode resubmission would not be visible.
Cliff-tested, Committee-approved. Merging.
> Feature move dmtcp reset

- code/Utilities/Templates/TemplateWorld.cpp
change WORLD_CLEAN to WORLD_{{MODULE_NAME}} in world template parameter declaration
> change world template file

- tools/mq.py
Added support for long-job mode to support case where some jobs finish in less than 4 hours
> long-job fix for less then 4-hour jobs
